// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdF4-7BibM8UPfjjhQui6L8QTcV58KvO8',
    appId: '1:799772657638:ios:a6066f567e1ab055a7f827',
    messagingSenderId: '799772657638',
    projectId: 'mt-myledger',
    storageBucket: 'mt-myledger.firebasestorage.app',
    iosBundleId: 'mt.myledger',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvQXmnJG39p-cV9d_M1lrvG99k3ATuy-A',
    appId: '1:799772657638:android:afdf04fbf5d60a9ba7f827',
    messagingSenderId: '799772657638',
    projectId: 'mt-myledger',
    storageBucket: 'mt-myledger.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfWxqGUi1ugJMh_MjjlCyDhT0qCcDvycE',
    appId: '1:799772657638:web:b5fef1bf82dcc04fa7f827',
    messagingSenderId: '799772657638',
    projectId: 'mt-myledger',
    authDomain: 'mt-myledger.firebaseapp.com',
    storageBucket: 'mt-myledger.firebasestorage.app',
    measurementId: 'G-BRX0Z9XEJ4',
  );
}
