
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD2FoTBJpQJKzELwOsCJ361Pl_AyHRLnM',
    appId: '1:861237053677:ios:77e29662a7c490bf4e64e4',
    messagingSenderId: '861237053677',
    projectId: 'myledger-f3313',
    storageBucket: 'myledger-f3313.firebasestorage.app',
    iosBundleId: 'mt.myledger',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgb6bLWzkfSGOQfpgxFcRv5awim_oadSA',
    appId: '1:861237053677:android:b3e3409be2b8042a4e64e4',
    messagingSenderId: '861237053677',
    projectId: 'myledger-f3313',
    storageBucket: 'myledger-f3313.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbC07ruBS-OBBjyYcbCvNJed4uE7x7oy4',
    appId: '1:861237053677:web:d902e730e83c74c94e64e4',
    messagingSenderId: '861237053677',
    projectId: 'myledger-f3313',
    authDomain: 'myledger-f3313.firebaseapp.com',
    storageBucket: 'myledger-f3313.firebasestorage.app',
    measurementId: 'G-676B7BTNXR',
  );

}